### ISSUE TITLE
 Flash Error: Error calling method on NPObject. - {}

### ISSUE THREAD

**Issue by jumptrnr** [jwagener-soundcloud/recorder.js#14]
Noticed this recently on Windows 8

Testing on:
http://recorderjs.ponyho.st/test/test.html

Chrome Results are:
Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11

Audio start, stop, progress (1, 0, 1)Rerun
Died on test #1: Error calling method on NPObject. - {}

IE 10 Results are:
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; .NET4.0E; .NET4.0C)

Audio start, stop, progress (1, 0, 1)Rerun1.Died on test #1:  - {
  "description": "",
  "number": -2147467259,
  "stack": "Error
   at Anonymous function (Unknown script code:49:5)
   at record (http://recorderjs.ponyho.st/recorder.js:46:5)
   at recordForSeconds (http://recorderjs.ponyho.st/test/test.js:23:5)
   at Anonymous function (http://recorderjs.ponyho.st/test/test.js:37:5)
   at run (http://recorderjs.ponyho.st/test/qunit/qunit.js:106:4)
   at Anonymous function (http://recorderjs.ponyho.st/test/qunit/qunit.js:239:5)
   at process (http://recorderjs.ponyho.st/test/qunit/qunit.js:931:4)
   at synchronize (http://recorderjs.ponyho.st/test/qunit/qunit.js:921:3)
   at run (http://recorderjs.ponyho.st/test/qunit/qunit.js:238:4)
   at process (http://recorderjs.ponyho.st/test/qunit/qunit.js:931:4)"
}

Thanks in advance.

**Comment by jumptrnr** [comment]
A few more data points for you if this helps - thanks again for this code and for looking at this stuff.  Really, really appreciated.

(Windows 7 IE 8.0, Flash 11.3.300.257)
Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; InfoPath.3), 
Result: No Flash Prompt ever appears

---

(Windows 8 Chrome 23, Flash 11,5,31,2)
Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11 
Result: Died on test #1: Error calling method on NPObject. - {}

---

(Windows 8 IE 10, Flash 11,3,376,12)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; .NET4.0E; .NET4.0C) 
Result 1.Died on test #1:  - {
  "description": "",
  "number": -2147467259,
  "stack": "Error
   at Anonymous function (Unknown script code:49:5)
   at record (http://recorderjs.ponyho.st/recorder.js:46:5)

---

(Windows 8 Firefox 17, Flash 11,5,502,110 installed)ss
Mozilla/5.0 (Windows NT 6.2; rv:17.0) Gecko/17.0 Firefox/17.0
Result Died on test #1: undefined - "Error in Actionscript. Use a try/catch block to find error."

**Comment by jwagener** [comment]
hmm so far no luck to reproduce this with flash 11.5 on win7 with IE8, Chrome, FF :( And unfortunately I don't have a Win8 test environment at the moment. Could you try installing a debug version of Flash and see if you can get some more info on the error?

**Comment by jumptrnr** [comment]
Windows 8 Chrome 23 with native flash off and debug version installed:
ActionScript Error
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at Recorder/setupMicrophone()
    at Recorder/record()
    at Function/http://adobe.com/AS3/2006/builtin::apply()
    at flash.external::ExternalInterface$/_callIn()
    at Function/<anonymous>()

Firefox 17 says the same

Will try on Windows 7 box when I have access again.

**Comment by jumptrnr** [comment]
My bad.  Windows 8 errors would appear to be related to the fact that the mic wasn't detected properly.  Now that it is - all seems OK on Windows 8.  Will let you know if the same was occurring on Windows 7.

Sorry for the false alarm there.

**Comment by jwagener** [comment]
Alright! Will see if it can fail more gracefully in that case

**Comment by rrahlf** [comment]
I've just recently run into this issue as well.  If the mic isn't detected, or one simply is not plugged in, flash fails with the null object reference jumptrnr posted.  With the debug version of flash we'll get the error dialog, but with the standard version the error is passed on to JS with little information.  JS logs an error in the console silently, and for the user - they see nothing.

Would it be possible to pass any ActionScript errors out to JavaScript so the application can display a friendly message to the user?  In this case particularly, a simple "Are you sure your microphone is plugged in?" message would be a huge help.

It's been a while since I've worked in ActionScript, but I'd be willing to request a pull and take a look if you like.

Thanks,
Ryan

**Comment by joelataylor** [comment]
This issue just popped up in Chrome Canary. I'm sure it's not a Recorder.js issue, but a browser one, however, it'd be nice to have the script produce an error message to the user if a mic is not detected.
